{
 "title": "Home Dashboard",
 "tags": [
  "Percona",
  "Insight"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=~\"node_load1|process_start_time_seconds\"}, instance)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "content": "<br>\n<div class=\"text-center dashboard-header\">\n<img src=\"public/img/pmm-logo.svg\" height=\"60px\" width=\"60px\">\n  <span>Percona Monitoring and Management</span>\n</div>"
  },
  { "title": "General information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "content": "**Overview**  \n[Percona Monitoring and Management (PMM)](https://www.percona.com/pmm) is a free and open-source platform for managing and monitoring MySQL and MongoDB performance, and provides time-based analysis to ensure that your data works as efficiently as possible. \n\n**Documentation**  \nPlease consult the official [PMM documentation](https://www.percona.com/doc/percona-monitoring-and-management/index.html) to learn more about PMM. Also of interest are the [Release notes](https://www.percona.com/doc/percona-monitoring-and-management/release-notes/index.html) and [FAQ](https://www.percona.com/doc/percona-monitoring-and-management/faq.html) for common questions about PMM.\n\n**Community and Blogs**  \nOn the [PMM Community Forums](https://www.percona.com/forums/questions-discussions/percona-monitoring-and-management) you will find help from Perconians and the Community at large.  Further, we publish PMM announcements and use cases regularly on the [Percona Database Performance Blog](https://www.percona.com/blog/category/percona-monitoring-and-management/)  \n\n**Get Help from Percona**  \nAre you looking for assistance that comes with a response-time guarantee? Let our [Support team](https://www.percona.com/services/support?utm_source=pmm&utm_medium=web&utm_campaign=support_link)  help you!\nAlready a customer? Log in to your [Percona Support Portal](https://customers.percona.com) \n\n\n\n"
  },
  {
   "title": "Starred and Recently used Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 }
  },
  {
   "title": "Systems under monitoring",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Monitored DB Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((mysql_up{instance=~\"$host\"}) or (mongodb_up{instance=~\"$host\"}) or (pg_up{instance=~\"$host\"})) or vector(0)"
    }
   ]
  },
  {
   "type": "pmm-update-panel",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DB Instances UP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count((mysql_up{instance=~\"$host\"} == 1) or (mongodb_up{instance=~\"$host\"} == 1) or (pg_up{instance=~\"$host\"} == 1)) or vector(0)"
    }
   ]
  },
  {
   "title": "DB Instances Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count((mysql_up{instance=~\"$host\"} == 0) or (mongodb_up{instance=~\"$host\"} == 0) or (pg_up{instance=~\"$host\"} == 0)) or vector(0)"
    }
   ]
  },
  { "title": "Environment Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Host", "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 18 }, "content": "<b>All</b>" },
  {
   "title": "CPU Busy",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by () ((sum by (instance,cpu) ( (clamp_max(rate(node_cpu{instance=~\"$host\",mode!='idle',mode!=\"iowait\"}[$interval]),1)) or  \n(clamp_max(irate(node_cpu{instance=~\"$host\",mode!='idle',mode!=\"iowait\"}[5m]),1)) ))*100 or \nsum by () (avg_over_time(node_cpu_average{instance=~\"$host\",mode!=\"idle\", mode!=\"total\",mode!=\"idle\"}[$interval]) or \navg_over_time(node_cpu_average{instance=~\"$host\",mode!=\"idle\",mode!=\"total\",mode!=\"idle\"}[5m])))"
    }
   ]
  },
  {
   "title": "Mem Avail",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by () ((node_memory_MemAvailable{instance=~\"$host\"} or (node_memory_MemFree{instance=~\"$host\"} + node_memory_Buffers{instance=~\"$host\"} + node_memory_Cached{instance=~\"$host\"})) / node_memory_MemTotal{instance=~\"$host\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 18 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by () (rate(node_vmstat_pgpgin{instance=~\"$host\"}[$interval]) or irate(node_vmstat_pgpgin{instance=~\"$host\"}[5m])) * 1024"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 18 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by () (rate(node_vmstat_pgpgout{instance=~\"$host\"}[$interval]) or irate(node_vmstat_pgpgout{instance=~\"$host\"}[5m])) * 1024"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 18 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(rate(node_network_receive_bytes{instance=~\"$host\",device!=\"lo\"}[$interval]) \nor irate(node_network_receive_bytes{instance=~\"$host\",device!=\"lo\"}[5m]) \nor max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[$interval]) \nor max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[5m]))\n+\nsum(rate(node_network_transmit_bytes{instance=~\"$host\",device!=\"lo\"}[$interval]) \nor irate(node_network_transmit_bytes{instance=~\"$host\",device!=\"lo\"}[5m])\nor max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[$interval]) \nor max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "DB Conns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by () (max_over_time(mysql_global_status_threads_connected{instance=~\"$host\"}[$interval]) or \nmax_over_time(mongodb_mongod_connections{instance=~\"$host\",state=\"current\"}[$interval]) or\nsum by (instance) (max_over_time(pg_stat_database_numbackends{instance=~\"$host\"}[$interval])))"
    }
   ]
  },
  {
   "title": "DB QPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by () (\n(rate(mysql_global_status_queries{instance=~\"$host\"}[$interval]) or \nirate(mysql_global_status_queries{instance=~\"$host\"}[5m])) or \n(sum(rate(mongodb_mongod_op_counters_total{instance=~\"$host\",type!=\"command\"}[$interval])) or \nsum(irate(mongodb_mongod_op_counters_total{instance=~\"$host\",type!=\"command\"}[5m]))) or\n(sum(rate(pg_stat_database_xact_commit{instance=~\"$host\"}[$interval]) + rate(pg_stat_database_xact_rollback{instance=~\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_xact_commit{instance=~\"$host\"}[5m]) + irate(pg_stat_database_xact_rollback{instance=~\"$host\"}[5m])))\n)"
    }
   ]
  },
  {
   "title": "Virtual CPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(node_cpu{instance=~\"$host\",mode=~\"user\"}) or (1-absent(node_cpu{instance=~\"$host\",mode=~\"user\"}))) + sum(rdsosmetrics_General_numVCPUs{instance=~\"$host\"} or up * 0)"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 18 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by () (node_memory_MemTotal{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Host uptime",
   "type": "singlestat",
   "description": "AVG   Uptime for  `All`",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_time{instance=~\"$host\"} - node_boot_time{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "DB uptime",
   "type": "singlestat",
   "description": "AVG for  `All`",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 18 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg(mysql_global_status_uptime{instance=~\"$host\"} or \nmongodb_mongod_instance_uptime_seconds {instance=~\"$host\"} or \n(time() - process_start_time_seconds{instance=~\"$host\",job=~\"postgresql\"}))"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "host" },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 22 }, "content": "$host" },
  {
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "clamp_max(avg by (instance) \n(sum by (cpu) ( (clamp_max(rate(node_cpu{instance=~\"$host\",mode!='idle',mode!=\"iowait\"}[$interval]),1)) or\n(clamp_max(irate(node_cpu{instance=~\"$host\",mode!='idle',mode!=\"iowait\"}[5m]),1)) )),1) *100 or\nsum by () (\navg_over_time(node_cpu_average{instance=~\"$host\",mode!=\"idle\", mode!=\"total\",job=\"rds-enhanced\"}[$interval]) or \navg_over_time(node_cpu_average{instance=~\"$host\",mode!=\"idle\", mode!=\"total\",job=\"rds-enhanced\"}[5m]))"
    }
   ]
  },
  {
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(node_memory_MemAvailable{instance=~\"$host\"} or \n(node_memory_MemFree{instance=~\"$host\"} + node_memory_Buffers{instance=~\"$host\"} + node_memory_Cached{instance=~\"$host\"})) / \nnode_memory_MemTotal{instance=~\"$host\"} * 100"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 22 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(node_vmstat_pgpgin{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$host\"}[5m]) * 1024"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 22 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(node_vmstat_pgpgout{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$host\"}[5m]) * 1024"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 22 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(sum(rate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[$interval]) or\nirate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[5m]))) + \n(sum(rate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[$interval]) or \nirate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[5m]))) "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum((max_over_time(mysql_global_status_threads_connected{instance=~\"$host\"}[$interval]) or \nmax_over_time(mysql_global_status_threads_connected{instance=~\"$host\"}[5m])) or\n(max_over_time(mongodb_mongod_connections{instance=~\"$host\", state=\"current\"}[$interval]) or\nmax_over_time(mongodb_mongod_connections{instance=~\"$host\", state=\"current\"}[5m])) or\n(sum by (instance) (max_over_time(pg_stat_database_numbackends{instance=~\"$host\"}[$interval])) or \nsum by (instance) (max_over_time(pg_stat_database_numbackends{instance=~\"$host\"}[5m]))))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum((rate(mysql_global_status_queries{instance=~\"$host\"}[$interval]) or \nirate(mysql_global_status_queries{instance=~\"$host\"}[5m])) or \n(sum(rate(mongodb_mongod_op_counters_total{instance=~\"$host\", type!=\"command\"}[$interval])) or \nsum(irate(mongodb_mongod_op_counters_total{instance=~\"$host\", type!=\"command\"}[5m]))) or\n(sum(rate(pg_stat_database_xact_commit{instance=~\"$host\"}[$interval]) + rate(pg_stat_database_xact_rollback{instance=~\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_xact_commit{instance=~\"$host\"}[5m]) + irate(pg_stat_database_xact_rollback{instance=~\"$host\"}[5m]))))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(node_cpu{instance=~\"$host\",mode=~\"user\"}) or (1-absent(node_cpu{instance=~\"$host\",mode=~\"user\"}))) + \nsum(rdsosmetrics_General_numVCPUs{instance=~\"$host\"} or up * 0)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 22 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 22 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "node_time{instance=~\"$host\"} - node_boot_time{instance=~\"$host\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 22 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(1,(mysql_global_status_uptime{instance=~\"$host\"} or \nmongodb_mongod_instance_uptime_seconds {instance=~\"$host\"} or \n(time() - process_start_time_seconds{instance=~\"$host\",job=~\"postgresql\"})))"
    }
   ]
  },
  {
   "title": "IO Thread Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(min_over_time(mysql_slave_status_slave_io_running{instance=~\"$host\"}[$interval]) or min_over_time(mysql_slave_status_slave_io_running{instance=~\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "SQL Thread Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(min_over_time(mysql_slave_status_slave_sql_running{instance=~\"$host\"}[$interval]) or min_over_time(mysql_slave_status_slave_sql_running{instance=~\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "Replication Error No",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(mysql_slave_status_last_errno{instance=~\"$host\"}[$interval]) or max_over_time(mysql_slave_status_last_errno{instance=~\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "Read Only",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(min_over_time(mysql_global_variables_read_only{instance=~\"$host\"}[$interval]) or min_over_time(mysql_global_variables_read_only{instance=~\"$host\"}[5m]))"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 28 }, "content": "$host" },
  {
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 28 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "clamp_max(avg by (instance) \n(sum by (cpu) ( (clamp_max(rate(node_cpu{instance=~\"$host\",mode!='idle',mode!=\"iowait\"}[$interval]),1)) or\n(clamp_max(irate(node_cpu{instance=~\"$host\",mode!='idle',mode!=\"iowait\"}[5m]),1)) )),1) *100 or\nsum by () (\navg_over_time(node_cpu_average{instance=~\"$host\",mode!=\"idle\", mode!=\"total\",job=\"rds-enhanced\"}[$interval]) or \navg_over_time(node_cpu_average{instance=~\"$host\",mode!=\"idle\", mode!=\"total\",job=\"rds-enhanced\"}[5m]))"
    }
   ]
  },
  {
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 28 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(node_memory_MemAvailable{instance=~\"$host\"} or \n(node_memory_MemFree{instance=~\"$host\"} + node_memory_Buffers{instance=~\"$host\"} + node_memory_Cached{instance=~\"$host\"})) / \nnode_memory_MemTotal{instance=~\"$host\"} * 100"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 28 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(node_vmstat_pgpgin{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$host\"}[5m]) * 1024"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 28 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(node_vmstat_pgpgout{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$host\"}[5m]) * 1024"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 28 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(sum(rate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[$interval]) or\nirate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[5m]))) + \n(sum(rate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[$interval]) or \nirate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[5m]))) "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum((max_over_time(mysql_global_status_threads_connected{instance=~\"$host\"}[$interval]) or \nmax_over_time(mysql_global_status_threads_connected{instance=~\"$host\"}[5m])) or\n(max_over_time(mongodb_mongod_connections{instance=~\"$host\", state=\"current\"}[$interval]) or\nmax_over_time(mongodb_mongod_connections{instance=~\"$host\", state=\"current\"}[5m])) or\n(sum by (instance) (max_over_time(pg_stat_database_numbackends{instance=~\"$host\"}[$interval])) or \nsum by (instance) (max_over_time(pg_stat_database_numbackends{instance=~\"$host\"}[5m]))))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum((rate(mysql_global_status_queries{instance=~\"$host\"}[$interval]) or \nirate(mysql_global_status_queries{instance=~\"$host\"}[5m])) or \n(sum(rate(mongodb_mongod_op_counters_total{instance=~\"$host\", type!=\"command\"}[$interval])) or \nsum(irate(mongodb_mongod_op_counters_total{instance=~\"$host\", type!=\"command\"}[5m]))) or\n(sum(rate(pg_stat_database_xact_commit{instance=~\"$host\"}[$interval]) + rate(pg_stat_database_xact_rollback{instance=~\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_xact_commit{instance=~\"$host\"}[5m]) + irate(pg_stat_database_xact_rollback{instance=~\"$host\"}[5m]))))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(node_cpu{instance=~\"$host\",mode=~\"user\"}) or (1-absent(node_cpu{instance=~\"$host\",mode=~\"user\"}))) + \nsum(rdsosmetrics_General_numVCPUs{instance=~\"$host\"} or up * 0)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 28 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 28 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "node_time{instance=~\"$host\"} - node_boot_time{instance=~\"$host\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 28 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(1,(mysql_global_status_uptime{instance=~\"$host\"} or \nmongodb_mongod_instance_uptime_seconds {instance=~\"$host\"} or \n(time() - process_start_time_seconds{instance=~\"$host\",job=~\"postgresql\"})))"
    }
   ]
  },
  {
   "title": "IO Thread Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(min_over_time(mysql_slave_status_slave_io_running{instance=~\"$host\"}[$interval]) or min_over_time(mysql_slave_status_slave_io_running{instance=~\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "SQL Thread Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(min_over_time(mysql_slave_status_slave_sql_running{instance=~\"$host\"}[$interval]) or min_over_time(mysql_slave_status_slave_sql_running{instance=~\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "Replication Error No",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(mysql_slave_status_last_errno{instance=~\"$host\"}[$interval]) or max_over_time(mysql_slave_status_last_errno{instance=~\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "Read Only",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(min_over_time(mysql_global_variables_read_only{instance=~\"$host\"}[$interval]) or min_over_time(mysql_global_variables_read_only{instance=~\"$host\"}[5m]))"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 34 }, "content": "$host" },
  {
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 34 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "clamp_max(avg by (instance) \n(sum by (cpu) ( (clamp_max(rate(node_cpu{instance=~\"$host\",mode!='idle',mode!=\"iowait\"}[$interval]),1)) or\n(clamp_max(irate(node_cpu{instance=~\"$host\",mode!='idle',mode!=\"iowait\"}[5m]),1)) )),1) *100 or\nsum by () (\navg_over_time(node_cpu_average{instance=~\"$host\",mode!=\"idle\", mode!=\"total\",job=\"rds-enhanced\"}[$interval]) or \navg_over_time(node_cpu_average{instance=~\"$host\",mode!=\"idle\", mode!=\"total\",job=\"rds-enhanced\"}[5m]))"
    }
   ]
  },
  {
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 34 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(node_memory_MemAvailable{instance=~\"$host\"} or \n(node_memory_MemFree{instance=~\"$host\"} + node_memory_Buffers{instance=~\"$host\"} + node_memory_Cached{instance=~\"$host\"})) / \nnode_memory_MemTotal{instance=~\"$host\"} * 100"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 34 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(node_vmstat_pgpgin{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$host\"}[5m]) * 1024"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 34 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(node_vmstat_pgpgout{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$host\"}[5m]) * 1024"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 34 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(sum(rate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[$interval]) or\nirate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[5m]))) + \n(sum(rate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[$interval]) or \nirate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[5m]))) "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 34 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum((max_over_time(mysql_global_status_threads_connected{instance=~\"$host\"}[$interval]) or \nmax_over_time(mysql_global_status_threads_connected{instance=~\"$host\"}[5m])) or\n(max_over_time(mongodb_mongod_connections{instance=~\"$host\", state=\"current\"}[$interval]) or\nmax_over_time(mongodb_mongod_connections{instance=~\"$host\", state=\"current\"}[5m])) or\n(sum by (instance) (max_over_time(pg_stat_database_numbackends{instance=~\"$host\"}[$interval])) or \nsum by (instance) (max_over_time(pg_stat_database_numbackends{instance=~\"$host\"}[5m]))))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 34 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum((rate(mysql_global_status_queries{instance=~\"$host\"}[$interval]) or \nirate(mysql_global_status_queries{instance=~\"$host\"}[5m])) or \n(sum(rate(mongodb_mongod_op_counters_total{instance=~\"$host\", type!=\"command\"}[$interval])) or \nsum(irate(mongodb_mongod_op_counters_total{instance=~\"$host\", type!=\"command\"}[5m]))) or\n(sum(rate(pg_stat_database_xact_commit{instance=~\"$host\"}[$interval]) + rate(pg_stat_database_xact_rollback{instance=~\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_xact_commit{instance=~\"$host\"}[5m]) + irate(pg_stat_database_xact_rollback{instance=~\"$host\"}[5m]))))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(node_cpu{instance=~\"$host\",mode=~\"user\"}) or (1-absent(node_cpu{instance=~\"$host\",mode=~\"user\"}))) + \nsum(rdsosmetrics_General_numVCPUs{instance=~\"$host\"} or up * 0)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 34 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 34 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "node_time{instance=~\"$host\"} - node_boot_time{instance=~\"$host\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 34 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(1,(mysql_global_status_uptime{instance=~\"$host\"} or \nmongodb_mongod_instance_uptime_seconds {instance=~\"$host\"} or \n(time() - process_start_time_seconds{instance=~\"$host\",job=~\"postgresql\"})))"
    }
   ]
  },
  {
   "title": "IO Thread Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(min_over_time(mysql_slave_status_slave_io_running{instance=~\"$host\"}[$interval]) or min_over_time(mysql_slave_status_slave_io_running{instance=~\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "SQL Thread Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(min_over_time(mysql_slave_status_slave_sql_running{instance=~\"$host\"}[$interval]) or min_over_time(mysql_slave_status_slave_sql_running{instance=~\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "Replication Error No",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(mysql_slave_status_last_errno{instance=~\"$host\"}[$interval]) or max_over_time(mysql_slave_status_last_errno{instance=~\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "Read Only",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(min_over_time(mysql_global_variables_read_only{instance=~\"$host\"}[$interval]) or min_over_time(mysql_global_variables_read_only{instance=~\"$host\"}[5m]))"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 40 }, "content": "$host" },
  {
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 40 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "clamp_max(avg by (instance) \n(sum by (cpu) ( (clamp_max(rate(node_cpu{instance=~\"$host\",mode!='idle',mode!=\"iowait\"}[$interval]),1)) or\n(clamp_max(irate(node_cpu{instance=~\"$host\",mode!='idle',mode!=\"iowait\"}[5m]),1)) )),1) *100 or\nsum by () (\navg_over_time(node_cpu_average{instance=~\"$host\",mode!=\"idle\", mode!=\"total\",job=\"rds-enhanced\"}[$interval]) or \navg_over_time(node_cpu_average{instance=~\"$host\",mode!=\"idle\", mode!=\"total\",job=\"rds-enhanced\"}[5m]))"
    }
   ]
  },
  {
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 40 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(node_memory_MemAvailable{instance=~\"$host\"} or \n(node_memory_MemFree{instance=~\"$host\"} + node_memory_Buffers{instance=~\"$host\"} + node_memory_Cached{instance=~\"$host\"})) / \nnode_memory_MemTotal{instance=~\"$host\"} * 100"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 40 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(node_vmstat_pgpgin{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$host\"}[5m]) * 1024"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 40 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(node_vmstat_pgpgout{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$host\"}[5m]) * 1024"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 40 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(sum(rate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[$interval]) or\nirate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[5m]))) + \n(sum(rate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[$interval]) or \nirate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[5m]))) "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 40 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum((max_over_time(mysql_global_status_threads_connected{instance=~\"$host\"}[$interval]) or \nmax_over_time(mysql_global_status_threads_connected{instance=~\"$host\"}[5m])) or\n(max_over_time(mongodb_mongod_connections{instance=~\"$host\", state=\"current\"}[$interval]) or\nmax_over_time(mongodb_mongod_connections{instance=~\"$host\", state=\"current\"}[5m])) or\n(sum by (instance) (max_over_time(pg_stat_database_numbackends{instance=~\"$host\"}[$interval])) or \nsum by (instance) (max_over_time(pg_stat_database_numbackends{instance=~\"$host\"}[5m]))))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 40 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum((rate(mysql_global_status_queries{instance=~\"$host\"}[$interval]) or \nirate(mysql_global_status_queries{instance=~\"$host\"}[5m])) or \n(sum(rate(mongodb_mongod_op_counters_total{instance=~\"$host\", type!=\"command\"}[$interval])) or \nsum(irate(mongodb_mongod_op_counters_total{instance=~\"$host\", type!=\"command\"}[5m]))) or\n(sum(rate(pg_stat_database_xact_commit{instance=~\"$host\"}[$interval]) + rate(pg_stat_database_xact_rollback{instance=~\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_xact_commit{instance=~\"$host\"}[5m]) + irate(pg_stat_database_xact_rollback{instance=~\"$host\"}[5m]))))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(node_cpu{instance=~\"$host\",mode=~\"user\"}) or (1-absent(node_cpu{instance=~\"$host\",mode=~\"user\"}))) + \nsum(rdsosmetrics_General_numVCPUs{instance=~\"$host\"} or up * 0)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 40 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 40 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "node_time{instance=~\"$host\"} - node_boot_time{instance=~\"$host\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 40 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(1,(mysql_global_status_uptime{instance=~\"$host\"} or \nmongodb_mongod_instance_uptime_seconds {instance=~\"$host\"} or \n(time() - process_start_time_seconds{instance=~\"$host\",job=~\"postgresql\"})))"
    }
   ]
  },
  {
   "title": "IO Thread Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(min_over_time(mysql_slave_status_slave_io_running{instance=~\"$host\"}[$interval]) or min_over_time(mysql_slave_status_slave_io_running{instance=~\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "SQL Thread Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(min_over_time(mysql_slave_status_slave_sql_running{instance=~\"$host\"}[$interval]) or min_over_time(mysql_slave_status_slave_sql_running{instance=~\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "Replication Error No",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(mysql_slave_status_last_errno{instance=~\"$host\"}[$interval]) or max_over_time(mysql_slave_status_last_errno{instance=~\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "Read Only",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(min_over_time(mysql_global_variables_read_only{instance=~\"$host\"}[$interval]) or min_over_time(mysql_global_variables_read_only{instance=~\"$host\"}[5m]))"
    }
   ]
  }
 ]
}